services:
  miniterminal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:80"
    restart: unless-stopped
    container_name: miniterminal-web
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    container_name: miniterminal-backend
    expose:
      - "3001"
